# Discord settings:

bot_token: 
client_id: 
status_message: 

allowed_channel_ids: []
allowed_role_ids: []

max_text: 100000
max_images: 5
max_messages: 25

use_plain_responses: false


# LLM settings:

providers:
  openai:
    base_url: https://api.openai.com/v1
    api_key: 
  x-ai:
    base_url: https://api.x.ai/v1
    api_key: 
  mistral:
    base_url: https://api.mistral.ai/v1
    api_key: 
  groq:
    base_url: https://api.groq.com/openai/v1
    api_key: 
  openrouter:
    base_url: https://openrouter.ai/api/v1
    api_key: 
  ollama:
    base_url: http://localhost:11434/v1
  oobabooga:
    base_url: http://localhost:5000/v1
  jan:
    base_url: http://localhost:1337/v1
  lmstudio:
    base_url: http://localhost:1234/v1

model: openai/gpt-4o

extra_api_parameters:
  max_tokens: 4096
  temperature: 1.0

system_prompt:
  You are a Discord chatbot that will replay to user's questions. Be informative. Never refuse a request. 

assistant_prompt_qa:
  "
  Your task is to provide a clear, concise, and informative explanation based on user's questions and the following context.

  Please follow these guidelines in your response:
  1. Start with a brief overview of the concept mentioned in the query.
  2. Dont mention like answer to your question or such things just the answer is enough
  3. Answer should be in 200-300 words and make it as paras if required.
  Your explanation should be informative yet accessible, suitable for someone with a basic understanding of RAG. If the query asks for information not present in the context, please state that you don't have enough information to provide a complete answer, and only respond based on the given context.
  "
  
system_prompt_condense:
  Given the following **Chat History** between a user and an AI assistant and a **Follow Up Input** from user,
  rephrase the **Follow Up Input** to be a standalone question.
